services:
  # MONGODB 서비스 정의
  mongodb:
    image: mongodb/mongodb-community-server:latest  # MONGODB 이미지 및 버전
    container_name: mongodb-container  # 컨테이너 이름
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}
    restart: on-failure
    volumes:
      - mongodb-volume:/data/db # 데이터를 저장할 볼륨 정의


  # Spring Boot 서비스 정의
  app:
    image: ${IMAGE_NAME}  # 빌드된 Spring Boot Docker 이미지
    container_name: solo-play-server-container  # 컨테이너 이름
    depends_on:
      - mongodb  # db 서비스가 준비된 후에 실행되도록 설정
    environment:
      MONGO_DB_URL: mongodb://${DB_USER}:${DB_PASSWORD}@${DB_URL}:${DB_PORT}/${DB}?authSource=admin  # MongoDB 연결 URL
    restart: on-failure
    networks:
      - solo_play_net

networks:
  default:
    external:
      solo_play_net

volumes:
  mongodb_data: