services:
  # MONGODB 서비스 정의
  mongodb:
    image: mongo  # MONGODB 이미지 및 버전
    container_name: solo-play-mongodb-container  # 컨테이너 이름
    volumes:
      - mongodb_data:/var/lib/mongo # 데이터를 저장할 볼륨 정의
    networks:
      - solo_play_net


  # Spring Boot 서비스 정의
  app:
    image: ${IMAGE_NAME}  # 빌드된 Spring Boot Docker 이미지
    container_name: solo-play-server-container  # 컨테이너 이름
    environment:
      MONGO_DB_NAME: ${DB_NAME}
      MONGO_DB_URL: ${DB_URL}
      MONGO_PORT: ${DB_PORT}

    depends_on:
      - mongodb
    networks:
      - solo_play_net
    ports:
      - "8080:8080"

volumes:
  mongodb_data:

networks:
  solo_play_net:
    name: solo_play_net
    external: true