spring:
  application:
    name: solo_play_web_server
  config:
    import: optional:file:.env[.properties]

  data:
    mongodb:
      uri: ${MONGO_DB_URL}

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
