spring:
  application:
    name: solo_play_web_server
  config:
    import: optional:file:.env[.properties]

  data:
    mongodb:
      uri: ${MONGO_DB_URL}

    redis:
      host: localhost
      port: 6379


  mail:
    protocol: smtp
    port: 587
    username: ${GOOGLE_ID}
    password: ${APP_PASSWORD}
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



springdoc:
  swagger-ui:
    path: /swagger-ui/index.html

jwt:
  secret-key: ${JWT_SECRET}
  access-token-expiry-ms: ${ACCESS_EXPIRY}
  refresh-token-expiry-ms: ${REFRESH_EXPIRY}
