spring:
  application:
    name: solo_play_web_server
  config:
    import: optional:file:.env[.properties]

  # r2dbc:
  #   url: ${MYSQL_URL}
  #   username: ${MYSQL_USER}
  #   password: ${MYSQL_PASSWORD}

  data:
    mongodb:
      uri: mongodb://${DB_USER}:${DB_PASSWORD}@${DB_URL}:${DB_PORT}/${DB}?authSource=admin

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
