CREATE TABLE IF NOT EXISTS member (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    nick_name VARCHAR(255) NOT NULL,
    gender VARCHAR(255) NOT NULL,
    birthday DATE NOT NULL,
    image_url VARCHAR(255) NOT NULL
);