CREATE TABLE IF NOT EXISTS palace (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    area VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    create_at TIMESTAMP(6) NOT NULL,
    urls VARCHAR(255) NOT NULL
);